name: build_variant
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^2.2.0
  dart_style: ^1.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
