name: build_variant
description: A new Flutter package project.
version: 0.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.1
  dart_style: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
